"use client";

import { useScrollReveal } from "@/lib/useScrollReveal";

function Reveal({
  className,
  children,
  style,
}: {
  className?: string;
  children: React.ReactNode;
  style?: React.CSSProperties;
}) {
  const ref = useScrollReveal();
  return (
    <div ref={ref} className={`fade-in-up ${className ?? ""}`} style={style}>
      {children}
    </div>
  );
}

/* ─── screenshot card (reused 4x in the grid) ─── */
function ScreenshotCard({
  title,
  alt,
  src,
  width,
  height,
  sizes,
}: {
  title: string;
  alt: string;
  src: string;
  width: number;
  height: number;
  sizes?: string;
}) {
  return (
    <Reveal>
      <div className="flex items-center gap-2.5 mb-2.5">
        <span className="w-0.75 h-4.5 bg-[#E8622B] rounded-full shrink-0" />
        <h3 className="text-[18px] md:text-[21px] font-semibold text-black tracking-[-0.02em]">
          {title}
        </h3>
      </div>
      <div className="bg-white rounded-[3px] shadow-[0_1px_6px_rgba(0,0,0,0.04)] hover:shadow-[0_3px_12px_rgba(0,0,0,0.07)] transition-shadow duration-500 overflow-hidden isolate">
        <img
          alt={alt}
          loading="lazy"
          width={width}
          height={height}
          decoding="async"
          className="w-full h-auto block rounded-[3px]"
          style={{ color: "transparent", clipPath: "inset(0 0 4px 4px round 3px)" }}
          sizes={sizes ?? "(max-width: 768px) 100vw, 50vw"}
          src={src}
        />
      </div>
    </Reveal>
  );
}

export default function WhatYouCanDo() {
  return (
    <>
      {/* ─── Heading bar ─── */}
      <section className="px-6 lg:px-10 xl:px-16 pt-10 pb-4 bg-white">
        <div className="flex flex-col items-center gap-3 sm:flex-row sm:justify-center sm:gap-4 max-w-5xl mx-auto w-full min-w-0">
          <img
            src="/claude-logo-pixels.png"
            alt="Claude AI"
            className="h-10 md:h-12 object-contain animate-spin shrink-0"
            style={{ animationDuration: "16s" }}
          />
          <h2 className="text-[28px] md:text-[36px] lg:text-[48px] font-bold tracking-[-0.03em] text-black text-center sm:text-left m-0 max-w-full min-w-0 text-balance">
            What you can do with Claude Connector?
          </h2>
        </div>
      </section>

      {/* ─── Screenshot cards grid + full-width audit ─── */}
      <section className="px-6 lg:px-10 xl:px-16 bg-white pt-6 pb-20 relative overflow-hidden">
        <div className="max-w-300 2xl:max-w-341.75 mx-auto relative z-10">
          {/* 2×2 grid */}
          <div className="grid grid-cols-1 md:grid-cols-2 gap-10 mb-10">
            <ScreenshotCard
              title="Weekly report"
              alt="Claude MCP weekly performance snapshot — Google Ads and Meta Ads spend, CPA, ROAS and anomalies"
              src="/mcp-weekly-snapshot.png"
              width={900}
              height={560}
            />
            <ScreenshotCard
              title="Cross-platform overlap"
              alt="Claude MCP showing Google Ads and Meta Ads audience overlap and cannibalization analysis"
              src="/mcp-overlap-platforms.png"
              width={900}
              height={560}
            />
            <ScreenshotCard
              title="True CPA analysis"
              alt="Claude MCP true CPA and ROAS by funnel stage with cross-platform deduplication"
              src="/mcp-cpa-by-funnel-stage.png"
              width={900}
              height={560}
            />
            <ScreenshotCard
              title="Budget allocation"
              alt="Claude MCP budget allocation by funnel stage and CPA reported vs deduplicated chart"
              src="/mcp-more-charts.png"
              width={900}
              height={560}
            />
          </div>

          {/* Account audit — full width */}
          <ScreenshotCard
            title="Account audit"
            alt="Full Google Ads account audit generated by Claude MCP"
            src="/mcp-example-of-audit-claude-mcp.png"
            width={1400}
            height={800}
            sizes="(max-width: 1200px) 100vw, 1200px"
          />
        </div>
      </section>

      {/* ─── Connect any AI tool with any ad account ─── */}
      <section className="pt-6 pb-10 bg-[#FAF9F6] overflow-x-hidden">
        <div className="max-w-6xl mx-auto text-center px-6 md:px-8 xl:px-16 pt-8 pb-9.5 w-full min-w-0">
          <Reveal className="mb-8 md:mb-10">
            <h3 className="text-[28px] md:text-[36px] lg:text-[42px] font-bold tracking-[-0.03em] leading-tight text-black text-center max-w-full px-1">
              Connect any AI tool with any ad account
            </h3>
          </Reveal>

          <div className="flex flex-col md:flex-row items-center justify-center gap-6 md:gap-0 w-full min-w-0">
            {/* AI tools */}
            <div className="flex flex-wrap md:flex-nowrap items-center justify-center gap-x-8 gap-y-6 md:gap-14 lg:gap-20 min-w-0 max-w-full">
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/claude-logo-pixels.png" alt="Claude" className="h-13 md:h-15 object-contain" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide">Claude</span>
              </div>
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/ChatGPT-Logo.png" alt="ChatGPT" className="h-12 md:h-14 object-contain" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide">ChatGPT</span>
              </div>
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/cursor-logo.png" alt="Cursor" className="h-12 md:h-14 object-contain invert" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide">Cursor</span>
              </div>
            </div>

            {/* Plus separator */}
            <span
              className="text-4xl md:text-5xl font-medium text-zinc-500 shrink-0 md:mx-10 lg:mx-16 md:-translate-y-3.5"
              aria-hidden="true"
            >
              +
            </span>

            {/* Ad platforms */}
            <div className="flex flex-wrap md:flex-nowrap items-center justify-center gap-x-8 gap-y-6 md:gap-14 lg:gap-20 min-w-0 max-w-full">
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/google_ads.png" alt="Google Ads" className="h-12 md:h-14 object-contain" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide text-center leading-tight">
                  Google<br />Ads
                </span>
              </div>
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/meta.png" alt="Meta Ads" className="h-12.5 md:h-14.75 object-contain" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide text-center leading-tight">
                  Meta<br />Ads
                </span>
              </div>
              <div className="flex flex-col items-center gap-3.5 min-w-0 shrink-0">
                <img src="/google-analytics.svg" alt="Google Analytics" className="h-12 md:h-14 object-contain" />
                <span className="text-[15px] sm:text-[18px] text-black font-semibold tracking-wide text-center leading-tight">
                  Google<br />Analytics
                </span>
              </div>
            </div>
          </div>
        </div>
      </section>
    </>
  );
}
